export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const UPDATE_PROJECT = "UDPATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const CLEAR_PROJECT = "CLEAR_PROJECT";
