GET http://localhost:4000/projects/all

###

GET http://localhost:4000/projects/602c73c80dcc7e0d84ff9009

###

POST http://localhost:4000/projects
Content-Type: application/json

{
    "title": "aaron's new website",
    "description": "my new project"
}

###

PATCH http://localhost:4000/projects/6025dcb5ae852d969b70d3ab
Content-Type: application/json

{
    "description": "Simple Web app for organizing coding projects"
}

###

DELETE http://localhost:4000/projects/6026d43a3c5321ae34ca7d73


