GET http://localhost:4000/projects

###

GET http://localhost:4000/projects/6026d3cb7074e3ae127a8e7e

###

POST http://localhost:4000/projects
Content-Type: application/json

{
    "title": "Clare Accounting Group12345678",
    "description": "static accounting website built for Scott and Carissa"
}

###

PATCH http://localhost:4000/projects/6025dcb5ae852d969b70d3ab
Content-Type: application/json

{
    "description": "Simple Web app for organizing coding projects"
}

###

DELETE http://localhost:4000/projects/6026d43a3c5321ae34ca7d73


